type: spec.insomnia.rest/5.0
schema_version: "5.1"
name: My 1st API
meta:
  id: wrk_ae9cae86cebb469fab59703ac2c0ff10
  created: 1778328512819
  modified: 1778334011397
  description: ""
collection:
  - name: Generate UUID
    meta:
      id: fld_839461aecfb64727b7c68ec977f093e2
      created: 1778334022699
      modified: 1778334185795
      sortKey: -1778334022699
      description: Creates a random UUID and returns it in a JSON structure
    children:
      - url: "{{ _.base_url }}/uuid"
        name: Return a UUID4.
        meta:
          id: req_6bfe3e7e29904e7ab3970f04ebd7bc02
          created: 1778334022701
          modified: 1778334154962
          isPrivate: false
          description: Generate and get an UUID
          sortKey: -1778334022701
        method: GET
        headers:
          - name: apikey
            value: "{{ _.apikey }}"
            disabled: false
        authentication:
          type: basic
          username: "{{ _.httpUsername }}"
          password: "{{ _.httpPassword }}"
        scripts:
          afterResponse: |+
            
            insomnia.test('Check if status is 200', () => {
                insomnia.expect(insomnia.response.code).to.eql(200);
            });

        settings:
          renderRequestBody: true
          encodeUrl: true
          followRedirects: global
          cookies:
            send: true
            store: true
          rebuildPath: true
  - name: Delayed Response
    meta:
      id: fld_164f912dea6a42bcbabd58dd7684a4bb
      created: 1778334022700
      modified: 1778334204291
      sortKey: -1778334022700
      description: ""
    children:
      - url: "{{ _.base_url }}/delay/0.01"
        name: Returns a delayed response (max of 10 seconds).
        meta:
          id: req_188dfd196cf7490e945cc15221ecdd75
          created: 1778334022702
          modified: 1778334203378
          isPrivate: false
          description: delay a responses by a defined number of secondes
          sortKey: -1778334022702
        method: GET
        headers:
          - name: apikey
            value: "{{ _.apikey }}"
            disabled: false
        authentication:
          type: basic
          username: "{{ _.httpUsername }}"
          password: "{{ _.httpPassword }}"
        scripts:
          afterResponse: |+
            
            insomnia.test('Check if status is 200', () => {
                insomnia.expect(insomnia.response.code).to.eql(200);
            });

        settings:
          renderRequestBody: true
          encodeUrl: true
          followRedirects: global
          cookies:
            send: true
            store: true
          rebuildPath: true
  - name: Query
    meta:
      id: fld_3a2fdeef8e9249648871f1d53db1f5a8
      created: 1778334022700
      modified: 1778334185735
      sortKey: -1778334022700
      description: ""
    children:
      - url: "{{ _.base_url }}/anything/query"
        name: Return anything data.
        meta:
          id: req_271db63460924c67aef6b27df3a25035
          created: 1778334022702
          modified: 1778334142363
          isPrivate: false
          description: returns all your query parameters
          sortKey: -1778334022702
        method: GET
        parameters:
          - name: exampleParam
            value: "1234"
            disabled: false
        headers:
          - name: apikey
            value: "{{ _.apikey }}"
            disabled: false
        authentication:
          type: basic
          username: "{{ _.httpUsername }}"
          password: "{{ _.httpPassword }}"
        scripts:
          afterResponse: |+
            
            insomnia.test('Check if status is 200', () => {
                insomnia.expect(insomnia.response.code).to.eql(200);
            });

        settings:
          renderRequestBody: true
          encodeUrl: true
          followRedirects: global
          cookies:
            send: true
            store: true
          rebuildPath: true
  - name: Anything
    meta:
      id: fld_ecb2a82bb2584fb7b27b4a52333fd447
      created: 1778334022700
      modified: 1778334185703
      sortKey: -1778334022700
      description: ""
    children:
      - url: "{{ _.base_url }}/anything"
        name: Return anything data.
        meta:
          id: req_fea7e862b5234714af944d22d4694598
          created: 1778334022701
          modified: 1778334138109
          isPrivate: false
          description: returns all your request
          sortKey: -1778334022701
        method: GET
        headers:
          - name: apikey
            value: "{{ _.apikey }}"
            disabled: false
        authentication:
          type: basic
          username: "{{ _.httpUsername }}"
          password: "{{ _.httpPassword }}"
        scripts:
          afterResponse: |+
            
            insomnia.test('Check if status is 200', () => {
                insomnia.expect(insomnia.response.code).to.eql(200);
            });

        settings:
          renderRequestBody: true
          encodeUrl: true
          followRedirects: global
          cookies:
            send: true
            store: true
          rebuildPath: true
      - url: "{{ _.base_url }}/anything/query"
        name: Return anything data.
        meta:
          id: req_56ec5110a3844ce2915ee2f619383615
          created: 1778334022702
          modified: 1778334133750
          isPrivate: false
          description: returns all your query parameters
          sortKey: -1778334022702
        method: GET
        parameters:
          - name: exampleParam
            value: "0"
            disabled: false
        headers:
          - name: apikey
            value: "{{ _.apikey }}"
            disabled: false
        authentication:
          type: basic
          username: "{{ _.httpUsername }}"
          password: "{{ _.httpPassword }}"
        scripts:
          afterResponse: |+
            
            insomnia.test('Check if status is 200', () => {
                insomnia.expect(insomnia.response.code).to.eql(200);
            });

        settings:
          renderRequestBody: true
          encodeUrl: true
          followRedirects: global
          cookies:
            send: true
            store: true
          rebuildPath: true
      - url: "{{ _.base_url }}/anything"
        name: Return anything data.
        meta:
          id: req_d1c13567f1a54de297e1571ea8468904
          created: 1778334022702
          modified: 1778334129120
          isPrivate: false
          description: returns all your request
          sortKey: -1778334022702
        method: POST
        body:
          mimeType: application/json
          text: |-
            {
              "client": "my client",
              "phone": "+330102030405"
            }
        headers:
          - name: Content-Type
            value: application/json
            disabled: false
          - name: apikey
            value: "{{ _.apikey }}"
            disabled: false
        authentication:
          type: basic
          username: "{{ _.httpUsername }}"
          password: "{{ _.httpPassword }}"
        scripts:
          afterResponse: |+
            
            insomnia.test('Check if status is 200', () => {
                insomnia.expect(insomnia.response.code).to.eql(200);
            });

        settings:
          renderRequestBody: true
          encodeUrl: true
          followRedirects: global
          cookies:
            send: true
            store: true
          rebuildPath: true
  - name: Status Codes
    meta:
      id: fld_87da2ee457774cf0851259e9f0f76d80
      created: 1778334022701
      modified: 1778334185591
      sortKey: -1778334022701
      description: ""
    children:
      - url: "{{ _.base_url }}/status/404"
        name: Return status code or random status code if more than one are given
        meta:
          id: req_f125e7293b5341579fb454c6f4554468
          created: 1778334022703
          modified: 1778334172908
          isPrivate: false
          description: returns a http status code
          sortKey: -1778334022703
        method: GET
        headers:
          - name: apikey
            value: "{{ _.apikey }}"
            disabled: false
        authentication:
          type: basic
          username: "{{ _.httpUsername }}"
          password: "{{ _.httpPassword }}"
        scripts:
          afterResponse: |+
            
            insomnia.test('Check if status is 404', () => {
                insomnia.expect(insomnia.response.code).to.eql(404);
            });

        settings:
          renderRequestBody: true
          encodeUrl: true
          followRedirects: global
          cookies:
            send: true
            store: true
          rebuildPath: true
cookieJar:
  name: Default Jar
  meta:
    id: jar_2d3ea89ed4ff51e68322c2c8402b1084347c4e74
    created: 1778328512823
    modified: 1778334204290
environments:
  name: Base Environment
  meta:
    id: env_2d3ea89ed4ff51e68322c2c8402b1084347c4e74
    created: 1778328512822
    modified: 1778334204290
    isPrivate: false
  data:
    base_url: "{{ _.scheme }}://{{ _.host }}{{ _.base_path }}"
  subEnvironments:
    - name: OpenAPI env httpbin.konghq.com
      meta:
        id: env_d7ff239fbe784e46bbd019876f06bf97
        created: 1778334022699
        modified: 1778334204290
        isPrivate: false
        sortKey: 1778334022699
      data:
        scheme: https
        base_path: ""
        host: httpbin.konghq.com
        apikey: apikey
        httpUsername: username
        httpPassword: password
spec:
  contents:
    openapi: 3.0.0
    servers:
      - url: https://httpbin.konghq.com
    info:
      contact:
        email: contact@konghq.com
        url: https://konghq.com
        name: Kong HQ
      title: My 1st API
      description: This is my first API, it is a simple API to test the OpenAPI
        specification (OAS insomnia 12.5)
      version: 1.0.0
    components:
      securitySchemes:
        basicAuth:
          type: http
          scheme: basic
        ApiKeyAuth:
          type: apiKey
          in: header
          name: apikey
    paths:
      /uuid:
        get:
          description: Generate and get an UUID
          operationId: get_uuid
          responses:
            "200":
              description: A UUID4.
          summary: Return a UUID4.
          tags:
            - Generate UUID
      /anything:
        get:
          description: returns all your request
          operationId: anything-GET
          responses:
            "200":
              description: The anything endpoint
          summary: Return anything data.
          tags:
            - Anything
        post:
          description: returns all your request
          operationId: anything-POST
          requestBody:
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - client
                    - phone
                  properties:
                    client:
                      type: string
                      example: my client
                    phone:
                      type: string
                      example: "+330102030405"
          responses:
            "200":
              description: The anything endpoint
          summary: Return anything data.
          tags:
            - Anything
      /anything/query:
        get:
          description: returns all your query parameters
          operationId: query
          parameters:
            - in: query
              name: exampleParam
              required: true
              schema:
                type: integer
                minimum: 5
                maximum: 25
              description: A value between 5 and 25
          responses:
            "200":
              description: The anything endpoint but with limitation on query
          summary: Return anything data.
          tags:
            - Anything
            - Query
      /delay/{delay_value}:
        get:
          description: delay a responses by a defined number of secondes
          operationId: delay
          parameters:
            - in: path
              name: delay_value
              required: true
              schema:
                type: integer
                minimum: 0
                maximum: 10
              description: The delay in seconds
          responses:
            "200":
              description: Returns a delayed response
          summary: Returns a delayed response (max of 10 seconds).
          tags:
            - Delayed Response
            - Path
      /status/{codes}:
        get:
          description: returns a http status code
          operationId: status_code
          parameters:
            - in: path
              name: codes
              required: true
              schema:
                type: integer
                minimum: 200
                maximum: 599
              description: The HTTP status code (200-599)
          responses:
            "200":
              description: Success
            "300":
              description: Redirection
            "400":
              description: Client errors
            "500":
              description: Server errors
          summary: Return status code or random status code if more than one are given
          tags:
            - Status Codes
            - Path
    tags:
      - description: Creates a random UUID and returns it in a JSON structure
        name: Generate UUID
      - name: Anything
      - name: Query
      - name: CatOrDog
      - name: Body
      - name: Delayed Response
      - name: Path
      - name: Status Codes
  meta:
    id: spc_87251b5574c74d0990ccff2eff24f085
    created: 1778328554989
    modified: 1778334588376
